config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'videos#index'

  resources :videos
  resources :peoples, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/image_concern.rb
module ImageConcern
  extend ActiveSupport::Concern

   BASE_URL = "https://image.tmdb.org/t/p/w500"

  def image_full_url
    if self.try(:image_url) || self.try(:profile_url)
      "#{BASE_URL}#{self.try(:image_url) || self.try(:profile_url)}"
    else
      return ActionController::Base.helpers.asset_path("no-image.png") unless ["Person", "Credit"].include? self.class.name
      return ActionController::Base.helpers.asset_path("person.png") if ["Person", "Credit"].include? self.class.name
    end
  end

end

app/models/credit.rb
class Credit < ApplicationRecord
   before_create :set_uuid

   include ::ImageConcern

   belongs_to :video, primary_key: :video_id
   has_one :person , primary_key: :people_id, foreign_key: :tmdb_people_id

   def set_uuid
     self.id = SecureRandom.uuid
   end
end

app/models/movie.rb
class Movie < ApplicationRecord
   before_create :set_uuid

   has_one :video, as: :media
   has_many :credits

   def set_uuid
     self.id = SecureRandom.uuid
   end
end

app/models/person.rb
class Person < ApplicationRecord
   before_create :set_uuid

   include ::ImageConcern

   has_many :credits, primary_key: :tmdb_people_id, foreign_key: :people_id

   def set_uuid
     self.id = SecureRandom.uuid
   end
end

app/models/tv_episode.rb
class TvEpisode < ApplicationRecord
   before_create :set_uuid

   include ::ImageConcern

   belongs_to :tv_show

   def set_uuid
     self.id = SecureRandom.uuid
   end
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
   before_create :set_uuid

   has_one :video, as: :media
   has_many :credits
   has_many :tv_episodes

   def set_uuid
     self.id = SecureRandom.uuid
   end
end

app/models/video.rb
class Video < ApplicationRecord
  before_create :set_uuid

  include ::ImageConcern

  belongs_to :media, polymorphic: true
  has_many :credits,  primary_key: :video_id

  default_scope { order(created_at: :desc) }

  def set_uuid
    self.id = SecureRandom.uuid
  end

  def original_video_title
    case media_type
    when "TvShow"
      media.original_name
    when "Movie"
      media.original_title
    else
      ""
    end
  end

  def video_title
    case media_type
    when "TvShow"
      media.name
    when "Movie"
      media.title
    else
      ""
    end
  end

  def actor_credits
    credits.where(job: "Actor")
  end

  def non_actor_credits
    credits.where.not(job: "Actor")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/peoples_controller.rb
class PeoplesController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /peoples
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @people = Person.find(params[:id])
  end

  # GET /peoples/new
  def new
    @person = Person.new
  end

  # GET /peoples/1/edit
  def edit
  end

  # POST /peoples
  # POST /peoples.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peoples/1
  # PATCH/PUT /peoples/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.fetch(:person, {})
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.page(params[:page]).per(20)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.fetch(:video, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%=  image_tag 'https://www.themoviedb.org/assets/2/v4/logos/primary-green-d70eebe18a5eb5b166d5c1ef0796715b8d1a2cbc698f96d311d62f894ae87085.svg', width: '30px', class: 'd-inline-block align-top' %>
    MBDB Listing
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieListing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- For bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  </head>

  <body> 
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/peoples/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/peoples/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/peoples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/peoples/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/peoples/show.html.erb
<h1><%= @people.name %></h1>

<%= image_tag @people.image_full_url, class: 'img-fluid img-thumbnail' %>

<h2 class="mt-3"> Credits </h2>
<div class="col-sm-10 row">
  <% @people.credits.each do |credit| %>
    <div class="col-sm-3 mb-3 border">
      <%= image_tag credit.video.image_full_url, class: "col-sm-11 img-fluid" %>
      <span class="col-sm-9">
        <%= credit.video.video_title%>
        (<%= credit.character %>)
      </span>
    </div>
  <% end %>
</div>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Videos</h1>

<div class="row">
  <% @videos.each do |video| %>
    <div class="col-sm-12 col-md-4 mb-5 border-bottom">
      <div class="col-sm-10">
        <%= image_tag  video.image_full_url, class: "col-sm-12 img-fluid" %>
        <span class="col-sm-2"></span>
        <span class="col-sm-8">
          <%= link_to video.video_title, video_path(video) %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<div class="col-sm-12">
  <div class="col-sm-12"><h1><%= @video.video_title %></h1></div>
  <%= image_tag @video.image_full_url, class: 'img-fluid' %>
</div>
<h2 class="mt-4">
  Description
</h2>
<%= @video.overview %>

<% if @video.media_type == "TvShow" %>
<h2 class="mt-4">
  Season & Episodes
</h2>
  <% @video.media.tv_episodes.pluck(:season_number).uniq.sort.each do |season_number| %>
    <div class="col-sm-10 row mb-4">
      <div class="col-sm-11">
        <h4> Season <%= season_number %> </h4>
      </div>
      <% seasons = @video.media.tv_episodes.where(season_number: season_number).order(:season_number) %>
      <% seasons.each do |season_epi| %>
        <div class="col-sm-3 mb-3 border-right">
          <%= image_tag season_epi.image_full_url, class: "img-fluid" %>
          Episode <%= season_epi.episode_number %> / <%= season_epi.air_date %> 
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
<h2>
  Credits
</h2>
<div class="col-sm-10 row">
  <div class="col-sm-12">
    <h4> Directors </h4>
  </div>
  <% @video.non_actor_credits.each do |credit| %>
    <div class="col-sm-3 mb-3 border">
      <%= link_to people_path(credit.person) do %>
        <%= image_tag credit.image_full_url, class: "col-sm-11 img-fluid" %>
      <% end %>
      <span class="col-sm-9">
        <%= credit.character %>
        (<%= credit.job %>)
      </span>
    </div>
  <% end %>
</div>
<div class="col-sm-11 row">
  <div class="col-sm-12">
    <h4> Actors </h4>
  </div>
  <% @video.actor_credits.each do |credit| %>
    <div class="col-sm-2 mb-3 mr-1 border-bottom">
      <%= link_to people_path(credit.person) do %>
        <%= image_tag credit.image_full_url, class: "col-sm-11 img-fluid" %>
      <% end %>
      <span class="col-sm-9">
        <%= credit.character %>
      </span>
    </div>
  <% end %>

</div>